# Generated by Django 2.2.16 on 2020-09-13 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('school', models.CharField(help_text='Enter the name of the College', max_length=200)),
                ('email', models.CharField(help_text='Enter your email', max_length=200)),
                ('location', models.CharField(help_text='Enter location of assault or harassment', max_length=200)),
                ('accused', models.CharField(help_text="Enter accuser's name or description", max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField()),
                ('tracking_number', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular report', primary_key=True, serialize=False)),
                ('date_of_report', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('s', 'Submitted'), ('ur', 'Under Review'), ('r', 'Reviewed'), ('rc', 'Reaching Conclusion'), ('c', 'Final Conclusion')], default='s', help_text='Status of report', max_length=2)),
            ],
        ),
    ]
